//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucHanh05_Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLiSinhVien : DbContext
    {
        public QuanLiSinhVien()
            : base("name=QuanLiSinhVien")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLDeTai> TBLDeTais { get; set; }
        public virtual DbSet<TBLGiangVien> TBLGiangViens { get; set; }
        public virtual DbSet<TBLHuongDan> TBLHuongDans { get; set; }
        public virtual DbSet<TBLKhoa> TBLKhoas { get; set; }
        public virtual DbSet<TBLSinhVien> TBLSinhViens { get; set; }
    }
}
