//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucHanh05_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLGiangVien()
        {
            this.TBLHuongDans = new HashSet<TBLHuongDan>();
        }
    
        public int Magv { get; set; }
        public string Hotengv { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public string Makhoa { get; set; }
    
        public virtual TBLKhoa TBLKhoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHuongDan> TBLHuongDans { get; set; }
    }
}
